// This script is designed to test the solidity smart contract - ArtSuppyChain.sol -- and the various functions within

// Using truffle-assertions to test emitted events
const truffleAssert = require('truffle-assertions');

// Assign the compiled smart contract artifact
var ArtSupplyChain = artifacts.require('ArtSupplyChain')

contract('ArtSupplyChain', function(accounts) {
    // Declare few constants and assign a few sample accounts generated by ganache-cli
    var artworkID = 0
    const contractOwner = accounts[0]
    const artworkOwnerID = accounts[1]
    const originArtistID = accounts[1]
    const originArtistName = "Dave Weindorf Ternisky"
    const originArtistInfo = "Abstract expressionist painter"
    const originArtistLocation = "Michigan, United States"
    const artworkTitle = "Clattering Teeth"
    const artworkYear = "2018"
    const artworkMedium = "Acrylic enamel and watercolor on canvas"
    const artworkStyle = "Abstract expressionism"
    const artistNotes = "Thinking of dentists and teeth"
    const artworkPrice = web3.utils.toWei('1', 'ether')
    var artworkState = 0
    const artAdopterID = accounts[2]
    const shipperID = accounts[3]
    const emptyAddress = '0x00000000000000000000000000000000000000'

    // Test: createArtwork()
    it("Testing smart contract function createArtwork() that allows an artist to create and define a new piece of art", async() => {
        const artSupplyChain = await ArtSupplyChain.deployed()

        // Mark an artwork as Created by calling function createArtwork()
        const result = await artSupplyChain.createArtwork(artworkTitle, artworkYear, artworkMedium, artworkStyle, originArtistID, originArtistName, originArtistInfo, originArtistLocation, artistNotes, {from: originArtistID})
        // Get the returned artworkID
        const artworkID = parseInt(result.logs[0].args.artworkID);

        // Verify event emitted
        truffleAssert.eventEmitted(result, 'Created');

        // Retrieve the owner of the newly-saved artwork from the blockchain
        const resultArtworkDetails = await artSupplyChain.fetchArtworkDetails.call(artworkID)

        assert.equal(parseInt(resultArtworkDetails[0]), 1, 'Invalid artwork ID')
        assert.equal(resultArtworkDetails[1], artworkOwnerID, 'Invalid artwork owner')
        assert.equal(resultArtworkDetails[2], artworkTitle, 'Invalid artwork title')
        assert.equal(resultArtworkDetails[3], artworkYear, 'Invalid artwork year')
        assert.equal(resultArtworkDetails[4], artworkStyle, 'Invalid artwork style')
        assert.equal(resultArtworkDetails[6], artistNotes, 'Invalid artist notes')
        assert.equal(resultArtworkDetails[7], 0, 'Invalid artwork state')
    })
    
    /*
    // Test: fetchArtistDetails()
    it("Testing smart contract function fetchArtistDetails() that allows anyone to fetch artist details for an artwork from blockchain", async() => {
        const artSupplyChain = await ArtSupplyChain.deployed()

        // Retrieve the newly-saved artist details from the blockchain
        const resultArtistDetails = await artSupplyChain.fetchArtistDetails.call(artworkID)

        // Verify the artist details result set
        assert.equal(resultArtistDetails[0], originArtistID, 'Invalid origin artistID')
        assert.equal(resultArtistDetails[1], originArtistName, 'Invalid origin artistName')
        assert.equal(resultArtistDetails[2], originArtistInfo, 'Invalid origin artistInfo')
    })

    // Test: fetchArtworkDetails()
    it("Testing smart contract function fetchArtworkDetails() that allows anyone to fetch artwork details from blockchain", async() => {
        const artSupplyChain = await ArtSupplyChain.deployed()

        // Retrieve the newly-saved artwork details from the blockchain
        const resultArtworkDetails = await artSupplyChain.fetchArtworkDetails.call(artworkID)

        // Verify the artwork details result set
        assert.equal(resultArtworkDetails[1], artworkTitle, 'Invalid artwork title')
        assert.equal(resultArtworkDetails[2], artworkYear, 'Invalid artwork year')
        assert.equal(resultArtworkDetails[3], artworkStyle, 'Invalid artwork style')
        assert.equal(resultArtworkDetails[4], artworkPrice, 'Invalid artwork price')
        assert.equal(resultArtworkDetails[5], artistNotes, 'Invalid artist notes')
        assert.equal(resultArtworkDetails[6], 0, 'Invalid artwork state')
        assert.equal(resultArtworkDetails[7], artAdopterID, 'Invalid artwork adopter ID')
        assert.equal(resultArtworkDetails[8], shipperID, 'Invalid shipper ID')
    })


    // Test: frameArtwork()
    it("Testing smart contract function frameArtwork() that allows an artist to frame the artwork", async() => {
        const artSupplyChain = await ArtSupplyChain.deployed()
    
        // State gets changed to 'Framed'
        await artSupplyChain.frameArtwork(artworkID, {from: originArtistID});    

        const state = await artSupplyChain.fetchArtworkState(artworkID);
        
        assert.equal(state, 1, 'State is not Framed')
    })
    
    // Test: adoptableArtwork()
    it("Testing smart contract function adoptableArtwork() that allows an artist to put an artwork up for adoption", async() => {
        const artSupplyChain = await ArtSupplyChain.deployed()
    
        // State gets changed to 'Adoptable'
        await artSupplyChain.adoptableArtwork(artworkID, {from: originArtistID});    

        const state = await artSupplyChain.fetchArtworkState(artworkID);
        
        assert.equal(state, 2, 'State is not Adoptable')
    })

    // Test: adoptArtwork()
    it("Testing smart contract function adoptArtwork() that allows a consumer to adopt an artwork", async() => {
        const artSupplyChain = await ArtSupplyChain.deployed()
    
        // State gets changed to 'Adopted'
        await artSupplyChain.adoptArtwork(artworkID, {from: artAdopterID});    

        // Retrieve the newly-saved artwork details from the blockchain
        const resultArtworkDetails = await artSupplyChain.fetchArtworkDetails.call(artworkID)

        // Verify the artwork owner, state, and adopter ID
        assert.equal(resultArtworkDetails[0], artAdopterID, 'Ownership not transferred to art adopter ID')
        assert.equal(resultArtworkDetails[5], 3, 'State is not Adopted')
        assert.equal(resultArtworkDetails[6], artAdopterID, 'Invalid artwork adopter ID')
    })

    // Test: packArtwork()
    it("Testing smart contract function packArtwork() that allows an artist to pack an artwork", async() => {
        const artSupplyChain = await ArtSupplyChain.deployed()
    
        // State gets changed to 'Packed'
        await artSupplyChain.packArtwork(artworkID, {from: originArtistID});    

        const state = await artSupplyChain.fetchArtworkState(artworkID);
        
        assert.equal(state, 4, 'State is not Packed')
    })        

    // Test: pickUpArtwork()
    it("Testing smart contract function pickUpArtwork() that allows a shipper to pick-up the artwork", async() => {
        const artSupplyChain = await ArtSupplyChain.deployed()
    
        // State gets changed to 'PickedUp'
        await artSupplyChain.pickUpArtwork(artworkID, {from: shipperID});    

        // Retrieve the newly-saved artwork details from the blockchain
        const resultArtworkDetails = await artSupplyChain.fetchArtworkDetails.call(artworkID)

        // Verify the artwork owner, state, and shipper ID
        assert.equal(resultArtworkDetails[0], shipperID, 'Ownership not transferred to shipper')
        assert.equal(resultArtworkDetails[5], 5, 'State is not PickedUp')
        assert.equal(resultArtworkDetails[7], shipperID, 'Invalid shipper ID')
    })    

    // Test: shipArtwork()
    it("Testing smart contract function shipArtwork() that allows a shipper to ship the artwork", async() => {
        const artSupplyChain = await ArtSupplyChain.deployed()
    
        // State gets changed to 'Shipped'
        await artSupplyChain.shipArtwork(artworkID, {from: shipperID});    

        // Retrieve the newly-saved artwork details from the blockchain
        const state = await artSupplyChain.fetchArtworkState(artworkID);
        
        assert.equal(state, 6, 'State is not Shipped')
    })    

    // Test: deliverArtwork()
    it("Testing smart contract function deliverArtwork() that allows a shipper to mark the artwork delivered", async() => {
        const artSupplyChain = await ArtSupplyChain.deployed()
    
        // State gets changed to 'Delivered'
        await artSupplyChain.deliverArtwork(artworkID, {from: shipperID});    

        // Retrieve the newly-saved artwork details from the blockchain
        const resultArtworkDetails = await artSupplyChain.fetchArtworkDetails.call(artworkID)

        // Verify the artwork owner, state, and art adopter ID
        assert.equal(resultArtworkDetails[0], artAdopterID, 'Ownership not transferred to art adopter')
        assert.equal(resultArtworkDetails[5], 7, 'State is not Delivered')
        assert.equal(resultArtworkDetails[6], artAdopterID, 'Invalid art adopter ID')
    }) 
    */   
});

